### ISSUE TITLE
Generate a random seed during the run

### ISSUE THREAD

**Issue by malabikasen** [Murali-group/supervised-grns#10]
Currently, the pipeline uses a random seed provided through the config file. We want the random seed to be generated during an active run of the code. 
Random seed through the config file should only be used to regenerate an old result or for debugging purposes.

**Comment by adyprat** [comment]
Thank you @malabikasen. I incorporated your suggestion to fix this in a clean commit. You can remove the branch since merging it into my code was a bit of a hassle.
